version: "3"
services:
  masstransit-mq:
    image: rabbitmq:management
    container_name: MassTransit.RabbitMq
    hostname: masstransit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3

  # masstransit-producer:
  #   image: masstransit-producer
  #   container_name: MassTransit.Producer
  #   depends_on:
  #     masstransit-mq:
  #       condition: service_healthy
  #   command: sh -c "sleep 30 && dotnet Producer.dll"

  # masstransit-consumer:
  #   image: masstransit-consumer
  #   container_name: MassTransit.Consumer
  #   depends_on:
  #     masstransit-mq:
  #       condition: service_healthy
  #   command: sh -c "sleep 30 && dotnet Consumer.dll"

  elasticsearch:
    container_name: elastic-search
    image: elasticsearch:8.13.4
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
volumes:
  elasticsearch-data:
