FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

COPY ./Consumer/Consumer.csproj ./Consumer/
COPY ./Contracts/Contracts.csproj ./Contracts/
RUN dotnet restore ./Consumer/Consumer.csproj

COPY ./Consumer ./Consumer
COPY ./Contracts ./Contracts/

WORKDIR /App/Consumer
RUN dotnet publish -c Release -o out

RUN ls out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/Consumer/out .

ENTRYPOINT ["dotnet", "Consumer.dll"]
